# Generated by Django 3.1.2 on 2020-12-03 09:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('title', models.CharField(help_text='Enter Book Title', max_length=200)),
                ('author', models.CharField(help_text='Enter Author', max_length=50)),
                ('publisher', models.CharField(help_text='Enter Publisher', max_length=50)),
                ('publication_date', models.DateField(blank=True, help_text='YYYY-MM-D', null=True)),
                ('cover_page', models.FileField(upload_to='')),
                ('seller', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
