# Generated by Django 3.1.2 on 2020-12-29 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksinventoryapp', '0003_auto_20201222_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Enter Book Quantity', validators=[django.core.validators.MaxValueValidator(9999)])),
                ('price', models.IntegerField(help_text='Enter Price of the Book', validators=[django.core.validators.MaxValueValidator(9999999999999)])),
            ],
        ),
    ]
