# Generated by Django 3.1.2 on 2020-12-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksinventoryapp', '0004_bookinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity_and_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mybookinfo', to='booksinventoryapp.bookinfo'),
        ),
    ]
