# Generated by Django 3.1.2 on 2020-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksinventoryapp', '0005_book_quantity_and_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(upload_to=''),
        ),
    ]
