# Generated by Django 3.1.2 on 2021-02-17 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksinventoryapp', '0006_auto_20201230_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
